export default [
  { name: "Snickers", age: 2, breed: "King Charles", size: "small", pic: "" },
  { name: "Hugo", age: 8, breed: "Labrador", size: "large", pic: "" },
  { name: "Bailey", age: 4, breed: "Beagle", size: "medium", pic: "" },
  { name: "Max", age: 5, breed: "Golden Retriever", size: "large", pic: "" },
  { name: "Bella", age: 3, breed: "Shih Tzu", size: "small", pic: "" },
  { name: "Milo", age: 2, breed: "Pug", size: "small", pic: "" },
  { name: "Daisy", age: 6, breed: "Bulldog", size: "medium", pic: "" },
  { name: "Rex", age: 7, breed: "German Shepherd", size: "large", pic: "" },
  { name: "Cooper", age: 4, breed: "Boxer", size: "large", pic: "" },
  { name: "Luna", age: 3, breed: "Dachshund", size: "small", pic: "" },
  { name: "Charlie", age: 5, breed: "Border Collie", size: "medium", pic: "" },
  { name: "Chloe", age: 6, breed: "Poodle", size: "medium", pic: "" },
  { name: "Rocky", age: 8, breed: "Rottweiler", size: "large", pic: "" },
  { name: "Lucy", age: 4, breed: "Corgi", size: "small", pic: "" },
  { name: "Toby", age: 1, breed: "Dalmatian", size: "large", pic: "" },
  { name: "Sadie", age: 3, breed: "Samoyed", size: "large", pic: "" },
  { name: "Bentley", age: 2, breed: "Husky", size: "large", pic: "" },
  { name: "Harley", age: 6, breed: "Chihuahua", size: "small", pic: "" },
  { name: "Zoe", age: 4, breed: "Shiba Inu", size: "small", pic: "" },
  { name: "Oscar", age: 5, breed: "Doberman", size: "large", pic: "" },
  { name: "Ruby", age: 2, breed: "Bichon Frise", size: "small", pic: "" },
  { name: "Maggie", age: 3, breed: "French Bulldog", size: "small", pic: "" },
  { name: "Buddy", age: 4, breed: "Great Dane", size: "large", pic: "" },
  { name: "Jack", age: 3, breed: "Pomeranian", size: "small", pic: "" },
  { name: "Roxy", age: 5, breed: "Cocker Spaniel", size: "medium", pic: "" },
  { name: "Finn", age: 2, breed: "Maltese", size: "small", pic: "" },
  { name: "Ellie", age: 6, breed: "Basset Hound", size: "medium", pic: "" },
  { name: "Bear", age: 7, breed: "Saint Bernard", size: "large", pic: "" },
  {
    name: "Scout",
    age: 3,
    breed: "Shetland Sheepdog",
    size: "medium",
    pic: "",
  },
  { name: "Zeus", age: 8, breed: "Alaskan Malamute", size: "large", pic: "" },
];
